version: '3.3'

services:
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: password
  web:
    build:
      context: .
    links:
      - db
    environment: &ENV
      RAILS_ENV: production 
      ROLLCALL_ROLE: web
      VIRTUAL_HOST: rollcall.docker
      DATABASE_URL: postgres://postgres:password@db:5432/rollcall_dev
      REDIS_URL: redis://10.0.4.15:6379
      # SENTRY_DSN: 'https://foo:bar@sentry.insops.net/35'
      SECRET_KEY_BASE: 'GSOC6DGMsvlLtDkaAagn7HBtxO4FJZECVYVuceZV7LMGMaYTIBXbK5OLa3UC'
      RESQUE_USER: 'admin'
      RESQUE_PASS: 'changeme'
      AWS_ACCESS_KEY_ID:  AKIA5CVS6BMFHY4H43PK
      AWS_SECRET_ACCESS_KEY: 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
      AWS_REGION: 'ap-southeast-1'
      AWS_BUCKET: canvas-omt-vn
      AWS_S3_ENDPOINT: s3.ap-southeast-1.amazonaws.com 
      LTI_KEY: '1BQjSm3JXjPRrqIIFWUhKgLD4ksBocQi'
      LTI_SECRET: 'dIaFTjNxzuHkmk5BfUgyw0Kd0eMDKzkg'
      LTI_REQUIRE_CANVAS: 'true'
    ports:
        - "8000:80"

  work:
    build:
      context: .
    links:
      - db
    environment:
      <<: *ENV
      ROLLCALL_ROLE: 'worker'
      QUEUE: "*"
    external_links:
      - ${PROXY_CONTAINER:-dinghy_http_proxy}:bucket.minio.rollcall-attendance.docker
